# 日本語設定
export LANG=ja_JP.UTF-8
export KCODE=u # Ruby用

# エディタ設定
export EDITOR=vim

# ユーザー実行ファイル
PATH=$PATH:$HOME/bin
PATH=$PATH:$HOME/local/bin
PATH=$PATH:$HOME/dotfiles/bin
export PATH

# ユーザーライブラリ
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib
export LD_LIBRARY_PATH

# ユーザーズマニュアル
MANPATH=$MANPATH:$HOME/local/share/man
export MANPATH

# Tree Charset
export TREE_CHARSET=C
