# キーバインドモード {
    # vim
    bindkey -v
    # emacs
    #bindkey -e
# }

# コマンド補完 {
    # 補完機能を有効にする
    autoload -U compinit; compinit
    # 補完候補を一覧で表示する(d)
    setopt auto_list
    # 補完キー連打で補完候補を順に表示する(d)
    setopt auto_menu
    # 補完候補をできるだけ詰めて表示する
    setopt list_packed
    # 補完候補にファイルの種類も表示する
    setopt list_types
    # グロブ機能を拡張する
    setopt extended_glob
    # ファイルグロブで大文字小文字を区別しない
    #unsetopt caseglob
    # 補完時に大文字小文字を区別しない
    #zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
    # Shift-Tabで補完候補を逆順する("\e[Z"でも動作する)
    bindkey "^[[Z" reverse-menu-complete
    # コマンドのスペルを訂正しない
    unsetopt correctall
# }

# コマンド履歴 {
    # ヒストリを保存するファイル
    HISTFILE=~/.zsh_history
    # メモリに保存されるヒストリの件数
    HISTSIZE=10000
    # 保存されるヒストリの件数
    SAVEHIST=1000000
    # !を使ったヒストリ展開を行う(d)
    setopt bang_hist
    # ヒストリに実行時間も保存する
    setopt extended_history
    # 直前と同じコマンドはヒストリに追加しない
    setopt hist_ignore_dups
    # 他のシェルのヒストリをリアルタイムで共有する
    setopt share_history
    # 余分なスペースを削除してヒストリに保存する
    setopt hist_reduce_blanks
# }

# コマンド検索 {
    autoload history-search-end
    zle -N history-beginning-search-backward-end history-search-end
    zle -N history-beginning-search-forward-end history-search-end
    bindkey "^P" history-beginning-search-backward-end
    bindkey "^N" history-beginning-search-forward-end
    bindkey "^R" history-incremental-pattern-search-backward
    bindkey "^S" history-incremental-pattern-search-forward
    stty stop undef # Ctrl+Sでの端末ストップを無効化（インクリメントサーチのため）
# }

# コマンド予測 {
  #autoload predict-on; predict-on
# }

# プロンプト設定 {
    autoload colors; colors
    local p_host="%F{blue}%B%n%b%f@%F{gray}%m%f"
    local p_mark="%(!,#,$)"
    local p_cdir="%F{green}%d%f"
    local p_date="%D %T"
    PROMPT="[$p_host]$p_mark "
    PROMPT2="> "
    RPROMPT="[$p_cdir] $p_date"
# }

# lsカラー設定 {
    export LSCOLORS=exfxcxdxbxegedabagacad
    export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
    export ZLS_COLORS=$LS_COLORS
    zstyle ':completion:*' list-colors 'di=34' 'ln=35' 'so=32' 'ex=31' 'bd=46;34' 'cd=43;34'
# }

# その他オプション {
    # ビープ音を鳴らさないようにする
    setopt no_beep
    # ディレクトリ名の入力のみで移動する
    setopt auto_cd
    # cd時にディレクトリスタックにpushdする
    setopt auto_pushd
    # =以降も補完する(--prefix=/usrなど)
    setopt magic_equal_subst
    # プロンプト定義内で変数置換やコマンド置換を扱う
    setopt prompt_subst
    # バックグラウンドジョブの状態変化を即時報告する
    setopt notify
    # =commandを`which command`と同じ処理にする
    setopt equals
    # 日本語ファイル名を表示可能にする
    setopt print_eight_bit
# }

# Alias {
    # ディレクトリ作成後、カレントディレクトリに
    function mkdircd() { mkdir -p "$@" && eval cd "\"\$$#\""; }
    # 色付きls
    case "${OSTYPE}" in
        darwin*) alias ls="ls -G" ;;
        linux*)  alias ls='ls --color' ;;
        *)       alias ls='ls' ;;
    esac
    # リストls
    alias ll="ls -l"
    # 隠しファイルリストls
    alias la="ls -al"
    # コマンド履歴全件表示
    alias ha="history -i 0"
    # git
    alias g="git"
    # tmux 256色
    alias t="tmux -2"
    # tmux アタッチ
    alias ta="t a"
    # vagrant rsync & vagrant ssh
    alias vssh="vagrant rsync-auto &> /dev/null & vagrant ssh && fg"
    # bundle exec (noglob)
    alias be="noglob bundle exec"
    # bundle exec spring (noglob)
    alias bes="noglob bundle exec spring"
    # brew
    alias brew-tree="brew list | xargs brew deps --tree"
    # npm
    alias npms="npm start"
    alias npme="npm run"
    alias npmt="npm run test:watch"
    # docker
    function docker_compose_clean() {
        docker rm -fv `docker-compose ps -q`
    }
    function docker_rm_all() {
        docker rm -fv `docker ps -aq`
    }
    function docker_rmi_none {
        docker rmi $(docker images -qf "dangling=true")
    }
    function docker_rm_build {
        docker rm `docker ps -a | grep '/bin/sh -c' | awk '{print $1}'`
    }
    function docker_machine_eval_env {
        eval $(docker-machine env ${1-default})
    }
    function docker_machine_eval_env_swarm {
        eval $(docker-machine env --swarm ${1-default})
    }
    alias fig="docker-compose"
    alias fige="fig exec"
    alias figa="fige app"
    alias figr="docker-compose run --rm"
    alias figra="figr app"
    alias fig-clean="docker_compose_clean"
    alias docker-rmall="docker_rm_all"
    alias docker-rminone="docker_rmi_none"
    alias docker-rmbuild="docker_rm_build"
    alias dom="docker-machine"
    alias dome="docker_machine_eval_env"
    alias domes="docker_machine_eval_env_swarm"
    alias domfault="eval \$(dom env default)"
    # Terraform
    alias tf="terraform"
    alias ter="terraform"
    # Haskell
    alias rhs="runhaskell Setup.hs"
    # php xdebug
    alias phpx="env XDEBUG_CONFIG='idekey=xdebug' php"
    # zshrc再読み込み
    alias rc="source ~/.zshrc; echo '.zshrc reloaded'"
    # vim 新セッション作成
    alias vimnew="rm -rf .vimsessions; mkdir .vimsessions; vim +SaveSession"
    alias vimn="vimnew"
    # MacOSX用 tmux経由でアプリを起動すると色々うまくいかない問題の解決法
    # http://dev.jgs.me/2015/01/06/atom-LSOpenURLsWithRole-error.html
    # http://qiita.com/itkrt2y/items/dee87c406617d1bd45a6
    alias reattach="which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"
    # export .env
    function expenv {
      export $(cat "${1:-.env}" | grep -v '^#' | grep -v '^$' | xargs)
    }
# }

# 外部アプリ用 {
    # tmux powerline 用 (https://github.com/erikw/tmux-powerline)
    PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'
    # rbenv
    if [ -d $HOME/.rbenv/bin ]; then
        export RBENV_ROOT=$HOME/.rbenv
        export PATH="$RBENV_ROOT/bin:$PATH"
        eval "$(rbenv init - zsh)"
        # @todo without using system
        export PATH="$RBENV_ROOT/shims:$PATH"
    fi
    # ndenv
    # if [ -d $HOME/.ndenv/bin ]; then
    #     export PATH="$HOME/.ndenv/bin:$PATH"
    #     export PATH=/Users/namikingsoft/.ndenv/shims::$PATH # TODO
    #     eval "$(ndenv init - zsh)"
    # fi
    # nvm
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    # tfenv
    if [ -d $HOME/.tfenv/bin ]; then
        export PATH="$HOME/.tfenv/bin:$PATH"
    fi
    # pyenv
    if [ -d $HOME/.pyenv/bin ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init - zsh)"
    fi
    # rvm
    if [ -s "$HOME/.rvm/scripts/rvm" ]; then
        $HOME/.rvm/scripts/rvm
    fi
    # curl https://sh.rustup.rs -sSf | sh
    if [ -s "$HOME/.cargo/env" ]; then
      source "$HOME/.cargo/env"
    fi

    # Add GHC 7.10.2 to the PATH, via https://ghcformacosx.github.io/
    export GHC_DOT_APP="/Applications/ghc-7.10.2.app"
    if [ -d "$GHC_DOT_APP" ]; then
        export PATH="${HOME}/.local/bin:${HOME}/.cabal/bin:${GHC_DOT_APP}/Contents/bin:${PATH}"
    fi
# }

# PATH環境変数設定 {
    # @todo zshenvだと、優先度がデフォルトより低くなるため、こっちに移動
    PATH=$HOME/bin:$PATH
    PATH=$HOME/local/bin:$PATH
    PATH=./bin:$PATH
    PATH=./sbin:$PATH
    PATH=./node_modules/.bin:$PATH
    export PATH
# }

# 外部ファイル読み込み {
    # ローカル用設定ファイル
    [[ -f ~/.zshrc.local ]] && source ~/.zshrc.local
# }

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/namikingsoft/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/namikingsoft/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/namikingsoft/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/namikingsoft/google-cloud-sdk/completion.zsh.inc'; fi

# Load keychain
ssh-add -K &> /dev/null
